name: Execute Tests Suite
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dome
        run: make dm
      - name: Test
        run: make test
